version: '3.8'

services:
  build-debug:
    build: .
    image: playable-build-debug
    container_name: playable-build-debug
    working_dir: /app
    volumes:
      # Mount template so you can edit files and see changes
      - ./template:/app
    stdin_open: true
    tty: true
    command: tail -f /dev/null

